{
    "types" : {
        "Press" : {
            pluralLabel: "Press",
        "Team Meeting" : {
            pluralLabel: "Team Meetings",
        "Dev Meeting" : {
            pluralLabel: "Dev Meetings",
        "Design Meeting" : {
            pluralLabel: "Design Meetings",
        "Test Event" : {
            pluralLabel: "Test Events",
        "Event" : {
            pluralLabel: "Events",
        "Hackathon" : {
            pluralLabel: "Hackathons",
        "Project Release" : {
            pluralLabel: "Project Releases",
        "Conference" : {
            pluralLabel: "Conferences",
        "Games Research" : {
            pluralLabel: "Games Research",
        }
        }
        }
        }
        }
        }
        }
        }
        }
        }
    },
    "properties": {
        "person" : {
            "valueType" : "item"
        }
    },
    "items" : [
//HACKATHONS
        {   "type" :                  "Hackathon",
            "label" :                 "STEM Video Game Challenge Hackathon '12",
            "discipline" :            "Hackathon",
            "date" :                  "2012-02-02",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon to garner interest and entrants for National STEM Video Game Challenge",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/stem12"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "STEM Video Game Challenge Hackathon '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-12-15",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon to garner interest and entrants for National STEM Video Game Challenge",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/stem11"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Election Night Hackathon '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-11-08",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Open event to watch real-time results of the election, and hack on open projects",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/election-night-hackathon-2011"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Software Freedom Day '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-09-17",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Open Hackathon and Lightning Talks ",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://softwarefreedomday.org"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "CrisisCampRoc Hackathon for Haiti",
            "discipline" :            "Hackathon",
            "date" :                  "2010-02-12",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon for Haiti relief",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://pages.e-democracy.org/DemocracyMap"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "DemocracyMaps Dev Camp Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2010-06-14",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "DemocracyMaps Dev Camp Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/crisiscamproc-hack-thon-haiti-follow"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Sunlight Foundation's Great American Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2009-12-12",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "RIT's local hackathon as a part of the Great American Hackathon event",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/great-american-hackathon-rit"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT OLPC HQ Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2010-07-28",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT goes to OLPC HQ!",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/hackathon"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Homestretch Hackathon Summer",
            "discipline" :            "Hackathon",
            "date" :                  "2010-08-04",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Homestretch Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/homestretchhackathon"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "SU Student Sandbox Open Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2012-07-28",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT rocks the Twilio API in Syracuse",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/su-twilio-hack-12"
        },

//PROJECT RELEASES
        {   "type" :                  "Project Release",
            "label" :                 "Lemonade Stand 2.1 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-12",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Version 2.1 of Lemonade Stand is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://blog.linkybook.com/2010/11/lemonade-stand-21-released.html"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Blocku Released",
            "discipline" :            "Project Release",
            "date" :                  "2011-02-22",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Blocku is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/Blocku"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Mathematical Adventure: Fortune Hunter Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-03-11",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Mathematical Adveture: Fortune Hunter is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/fortunehunter"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Transbot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-06",
            "relationship" :          "Project Release",
            "relationship-detail" :   "IRC translation tool Transbot is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "https://fedorahosted.org/transbot/"
        },
        {   "type" :                  "Project Release",
            "label" :                 "PacMath 2.0 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-02-25",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity PacMath version 2.0 is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/PacMath"
        },
        {   "type" :                  "Project Release",
            "label" :                 "OpenVideoChat Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-03-10",
            "relationship" :          "Project Release",
            "relationship-detail" :   "OpenVideoChat proof of concept demo",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/ovc"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Groovebot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-07-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Groovebot: A Grooveshark IRC bot",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://gitorious.org/jlew/groovebot"
        },
        {   "type" :                  "Project Release",
            "label" :                 "MediaWiki Visualization",
            "discipline" :            "Demo",
            "date" :                  "2010-05-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Visualization Demo of RITWiki",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.youtube.com/watch?v=Sau6l9TOhgk"
        },


//EVENTS
        {   "type" :                  "Event",
            "label" :                 "Digital Rochester Demo Night",
            "discipline" :            "Demo",
            "date" :                  "2011-11-01",
            "relationship" :          "Event",
            "relationship-detail" :   "Members of Digital Rochester came to see demonstrations from our students",
            "imageURL" :              "wrench.png",
            "url" :                   "http://beta.innovation.rit.edu/csi2/main/node/DigitalRochcester2011"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Rochester Web Startups Walk-through",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-11-28",
            "relationship" :          "Event",
            "relationship-detail" :   "Members of the Rochester Web Startups Meetup scouted our space for future meetings",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/Rochester-Web-Startups-Group/"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "StartupWeekendROC Committee Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-11",
            "relationship" :          "Event",
            "relationship-detail" :   "Steering Committee Meeting for StartupWeekendROC",
            "imageURL" :              "meeting.png",
            "url" :                   "http://rochester.startupweekend.org"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Hacks/HackersROC Committee Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-09",
            "relationship" :          "Event",
            "relationship-detail" :   "Steering Committee Meeting between D&C, WXXI, and FOSS@RIT",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/HackshackersROC/"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Hacks/HackersROC Kickoff Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Over 50 attendees, many of them real-life journalists, met at the CSI to talk future of news.",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/HackshackersROC/events/45260912/"
        },
        {   "type" :                  "Event",
            "label" :                 "Game-Mania @ Strong Museum of Play",
            "discipline" :            "Demo",
            "date" :                  "2011-11-05",
            "relationship" :          "Event",
            "relationship-detail" :   "Demo'd Educational Games developed for HFOSS course on the OLPC XO laptops",
            "imageURL" :              "Event.png",
            "url" :                   "http://games.rit.edu/videogamemania"
        },
        {   "type" :                  "Conference",
            "label" :                 "StartupWeekendSyracuse",
            "discipline" :            "Demo",
            "date" :                  "2011-11-04",
            "relationship" :          "Event",
            "relationship-detail" :   "Served as Technical Mentor, and Open Source Advisor",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://syracuse.startupweekend.org"
        },
        {   "type" :                  "Event",
            "label" :                 "Google Faculty Research Program Info Session",
            "discipline" :            "Demo",
            "date" :                  "2011-07-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Explored Future funding opportunities for FOSS@RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://research.google.com/university/relations/research_awards.html"
        },
        {   "type" :                  "Event",
            "label" :                 "SU Student Sandbox Demo Day",
            "discipline" :            "Demo",
            "date" :                  "2011-08-17",
            "relationship" :          "Event",
            "relationship-detail" :   "Tabled at SYR Tech Garden",
            "imageURL" :              "Event.png",
            "url" :                   "http://opensource.com/education/11/8/bridging-boxes-hacker-matchmaking-upstate-new-york-opensource-way"
        },
        {   "type" :                  "Event",
            "label" :                 "CIVX.us Monroe Elections Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-11-02",
            "relationship" :          "Event",
            "relationship-detail" :   "Live CIVX.us Monroe Elections Demo for WXXI",
            "imageURL" :              "Event.png",
            "url" :                   "http://innovationtrail.org/post/election-night-results"
        },
        {   "type" :                  "Conference",
            "label" :                 "IEEE International Games Innovation Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-11-04",
            "relationship" :          "Conference",
            "relationship-detail" :   "IEEE IGIC",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://ice-gic.ieee-cesoc.org/2011/index.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "Audio Engineering Society Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-10-24",
            "relationship" :          "Conference",
            "relationship-detail" :   "Game Audio Sessions",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.gamasutra.com/view/news/38070/When_Motion_Controllers_And_Sound_Design_Collide.php"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Undergrad Research Symposium - Best Paper in IT/Computing",
            "discipline" :            "Conference",
            "date" :                  "2011-08-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "Nate Case won 'Best Paper in IT/Computing for his work on the CIVX project",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/News2010.html"
        },
        {   "type" :                  "Conference",
            "label" :                 "Open Source Software Research Mini-Summit",
            "discipline" :            "Conference",
            "date" :                  "2011-08-24",
            "relationship" :          "Conference",
            "relationship-detail" :   "Meeting of prominant FOSS labs internationally",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://foss.rit.edu/files/Open_Source_Software_Research_Mini_Summit.pdf"
        },
        {   "type" :                  "Event",
            "label" :                 "RIT New Student Resource Fair",
            "discipline" :            "Demo",
            "date" :                  "2011-08-31",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Tabled at event for incoming freshmen",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/~w-orient/firstyear_highlights.php"
        },
        {   "type" :                  "Conference",
            "label" :                 "GOSCON - Government Open Source Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-08-23",
            "relationship" :          "Conference",
            "relationship-detail" :   "Represented FOSS@RIT in Washington D.C.",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://goscon.org/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2011-08-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "Presentation of Student Research Projects",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/index.html"
        },
        {   "type" :                  "Conference",
            "label" :                 "ACM SIGITE",
            "discipline" :            "Conference",
            "date" :                  "2011-10-20",
            "relationship" :          "Conference",
            "relationship-detail" :   "IT Educators Panel",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://opensource.com/education/11/10/foss-meets-it-education-acm-sigite"
        },
        {   "type" :                  "Conference",
            "label" :                 "Teaching Open Source Summit",
            "discipline" :            "Conference",
            "date" :                  "2010-10-29",
            "relationship" :          "Conference",
            "relationship-detail" :   "Teaching Open Source Summit",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://teachingopensource.org/index.php/TOSS09"
        },
        {   "type" :                  "Conference",
            "label" :                 "HFOSS Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-03-10",
            "relationship" :          "Conference",
            "relationship-detail" :   "Humanitarian FOSS Project Symposium",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.hfoss.org/hfoss2010/?q=node/10"
        },
        {   "type" :                  "Conference",
            "label" :                 "Frontiers in Education Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-10-27",
            "relationship" :          "Conference",
            "relationship-detail" :   "Frontiers in Education Conference",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.fie-conference.org/fie2010/Pages/letters.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "Personal Democracy Forum",
            "discipline" :            "Conference",
            "date" :                  "2010-06-05",
            "relationship" :          "Conference",
            "relationship-detail" :   "Personal Democracy Forum",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://personaldemocracy.com/personal-democracy-forum-2010-conference-was"
        },
        {   "type" :                  "Conference",
            "label" :                 "IEEE Games Innovation Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-12-21",
            "relationship" :          "Conference",
            "relationship-detail" :   "IEEE Games Innovation Conference",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://ice-gic.ieee-cesoc.org/2011/index.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "NTID Technology Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-06-21",
            "relationship" :          "Conference",
            "relationship-detail" :   "NTID Technology Symposium",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/ntid/vp/techsym/"
        },
        {   "type" :                  "Conference",
            "label" :                 "Engineer of the Future Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-11-14",
            "relationship" :          "Conference",
            "relationship-detail" :   "Engineer of the Future Conference",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://engineerofthefuture.illinois.edu/"
        },
        {   "type" :                  "Event",
            "label" :                 "ImagineRIT 2010",
            "discipline" :            "Event",
            "date" :                  "2010-05-01",
            "relationship" :          "Event",
            "relationship-detail" :   "ImagineRIT 2010",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/imagine/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Summer Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-08-13",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Summer Undergraduate Research Symposium",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Fall Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-11-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Fall Undergraduate Research Symposium",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
        {   "type" :                  "Conference",
            "label" :                 "Social Media and Communications Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-09-29",
            "relationship" :          "Conference",
            "relationship-detail" :   "Social Media and Communications Symposium",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.rit.edu/cla/smacs/"
        },
        {   "type" :                  "Event",
            "label" :                 "POSSE @ RIT",
            "discipline" :            "Event",
            "date" :                  "2010-06-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Professors' Open Source Summer Experience @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT/2010"
        },
        {   "type" :                  "Conference",
            "label" :                 "FOSSCon 2010",
            "discipline" :            "Conference",
            "date" :                  "2010-06-19",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://fosscon.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "Walter Bender Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-11-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Walter Bender Lecture as a part of the Dean's Lecture Series in Golisano",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.gccis.rit.edu/lecture-series"
        },
        {   "type" :                  "Event",
            "label" :                 "Richard Stallman Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-02-23",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/csi"
        },
        {   "type" :                  "Event",
            "label" :                 "Righteous Pictures Screening and Workshop",
            "discipline" :            "Event",
            "date" :                  "2010-10-01",
            "relationship" :          "Event",
            "relationship-detail" :   "Righteous Pictures Screening and Workshop",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/events/righteouspictures"
        },
        {   "type" :                  "Event",
            "label" :                 "Software Freedom Day 2010",
            "discipline" :            "Event",
            "date" :                  "2010-09-18",
            "relationship" :          "Event",
            "relationship-detail" :   "Software Freedom Day 2010 @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://softwarefreedomday.org/"
        },
        {   "type" :                  "Conference",
            "label" :                 "CapitolCamp Developer Summit",
            "discipline" :            "Conference",
            "date" :                  "2010-08-19",
            "relationship" :          "Conference",
            "relationship-detail" :   "CapitolCamp Developer Summit",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://barcamp.org/w/page/402087/CapitolCamp"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampRoc Fall '10",
            "discipline" :            "Conference",
            "date" :                  "2010-10-23",
            "relationship" :          "Conference",
            "relationship-detail" :   "Barcamp Rochester Fall 2010",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://barcamproc.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "RIT48",
            "discipline" :            "Event",
            "date" :                  "2010-03-19",
            "relationship" :          "Event",
            "relationship-detail" :   "RIT48 Start-up Competition",
            "imageURL" :              "Event.png",
            "url" :                   "http://rit48.com/index_old.html"
        },
        {   "type" :                  "Event",
            "label" :                 "ARM Developer Day",
            "discipline" :            "Event",
            "date" :                  "2010-12-02",
            "relationship" :          "Event",
            "relationship-detail" :   "ARM Developer Day @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://afmiee.wordpress.com/"
        },
        {   "type" :                  "Event",
            "label" :                 "RITpedia Wikithon",
            "discipline" :            "Event",
            "date" :                  "2010-05-15",
            "relationship" :          "Event",
            "relationship-detail" :   "RITpedia Wikithon",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/studentaffairs/ritpedia/wiki/Main_Page"
        },
        {   "type" :                  "Event",
            "label" :                 "InterlockROC & Co-working Rochester: Lightning Talks",
            "discipline" :            "Event",
            "date" :                  "2010-02-05",
            "relationship" :          "Event",
            "relationship-detail" :   "InterlockROC & Co-working Rochester: Lightning Talks",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/interlockroc-showcase-first-fridays-2510"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Connectology Leadership Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-04-09",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Connectology Leadership Conference",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://campuslife.rit.edu/leadership/connectology/conference.php"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Winter Hackfest",
            "discipline" :            "Hackathon",
            "date" :                  "2011-01-21",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Winter Hackfest",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/winterhackfest"
        },
        {   "type" :                  "Event",
            "label" :                 "InterlockROC Lightning Talks",
            "discipline" :            "Event",
            "date" :                  "2011-02-18",
            "relationship" :          "Event",
            "relationship-detail" :   "InterlockROC Lightning Talks",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/events/InterlockROCLightningTalks"
        },
        {   "type" :                  "Conference",
            "label" :                 "PYCon: Connecting the Python Community",
            "discipline" :            "Conference",
            "date" :                  "2011-03-09",
            "relationship" :          "Conference",
            "relationship-detail" :   "PYCon: Connecting the Python Community",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://us.pycon.org/2011/home/"
        },
        {   "type" :                  "Event",
            "label" :                 "Linux Installfest",
            "discipline" :            "Event",
            "date" :                  "2011-04-23",
            "relationship" :          "Event",
            "relationship-detail" :   "Linux Installfest",
            "imageURL" :              "Event.png",
            "url" :                   "http://installfest.org/"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Winter Wrap-up Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-02-18",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Winter Wrap-up Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/WWH"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Spring Opportunities Meeting",
            "discipline" :            "Event",
            "date" :                  "2011-03-09",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Spring Opportunities Meeting",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/spring2011"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampRoc Spring '11",
            "discipline" :            "Conference",
            "date" :                  "2011-04-16",
            "relationship" :          "Conference",
            "relationship-detail" :   "Spring 2011 Barcamp Rochester",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://www.barcamproc.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "GCCIS Undergrad Research Fellowship Application/Doc Sprint",
            "discipline" :            "Event",
            "date" :                  "2011-03-21",
            "relationship" :          "Event",
            "relationship-detail" :   "GCCIS Undergrad Research Fellowship Application/Doc Sprint",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/summer-research-app-sprint"
        },
        {   "type" :                  "Event",
            "label" :                 "StackOverflow Meetup",
            "discipline" :            "Event",
            "date" :                  "2011-04-06",
            "relationship" :          "Event",
            "relationship-detail" :   "StackOverflow Meetup",
            "imageURL" :              "Event.png",
            "url" :                   "http://blog.stackoverflow.com/2011/03/stack-overflow-meetups-april-6/"
        },
        {   "type" :                  "Event",
            "label" :                 "EdTechDay",
            "discipline" :            "Event",
            "date" :                  "2011-03-24",
            "relationship" :          "Event",
            "relationship-detail" :   "EdTechDay",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.ithaca.edu/edtechday"
        },
        {   "type" :                  "Conference",
            "label" :                 "TEDxBuffalo 2011",
            "discipline" :            "Conference",
            "date" :                  "2011-10-11",
            "relationship" :          "Conference",
            "relationship-detail" :   "TEDxBuffalo",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://bit.ly/tedxbuffalo-civx"
        },
        {   "type" :                  "Conference",
            "label" :                 "WeLiveNYSummit 2011",
            "discipline" :            "Conference",
            "date" :                  "2011-03-26",
            "relationship" :          "Conference",
            "relationship-detail" :   "WeLiveNYSummit 2011 - Transparency, Technology, and Gov2.0",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://unystartups.com/2011/03/22/promotional-video-we-live-ny-summit-2011/"
        },
        {   "type" :                  "Event",
            "label" :                 "Rochester Java User Group Meeting (RJUG)",
            "discipline" :            "Event",
            "date" :                  "2011-04-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Rochester Java User Group Meeting (RJUG)",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/283"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "RiseAboveTheCrowd Hackfest",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-27",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "RiseAboveTheCrowd Hackfest",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/node/290"
        },
        {   "type" :                  "Event",
            "label" :                 "ImagineRIT",
            "discipline" :            "Event",
            "date" :                  "2011-05-07",
            "relationship" :          "Event",
            "relationship-detail" :   "ImagineRIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/imagine/"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampROC Fall '11",
            "discipline" :            "Conference",
            "date" :                  "2011-10-22",
            "relationship" :          "Conference",
            "relationship-detail" :   "BarcampROC Fall 2011",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://BarcampROC.org"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Breakfast Send-off",
            "discipline" :            "Event",
            "date" :                  "2011-05-19",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Breakfast Send-off",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/296"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Summer Undergraduate Research Fellowship Kick-Off",
            "discipline" :            "Event",
            "date" :                  "2011-04-27",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Summer Undergraduate Research Fellowship Kick-Off",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/297"
        },
        {   "type" :                  "Event",
            "label" :                 "StartupROC Meeting",
            "discipline" :            "Event",
            "date" :                  "2011-06-07",
            "relationship" :          "Event",
            "relationship-detail" :   "StartupROC Meeting",
            "imageURL" :              "Event.png",
            "url" :                   "http://startupweekend.org/"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT POSSE Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-06-06",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT POSSE Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT & SU Student Sandbox Hackathon",
            "discipline" :            "Event",
            "date" :                  "2011-07-12",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT & SU Student Sandbox Hackathon",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.syracusestudentsandbox.com/"
        },
        {   "type" :                  "Event",
            "label" :                 "POSSE",
            "discipline" :            "Event",
            "date" :                  "2011-07-14",
            "relationship" :          "Event",
            "relationship-detail" :   "POSSE",
            "imageURL" :              "Event.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT"
        },
        {   "type" :                  "Conference",
            "label" :                 "FUDCon Blacksburg - Lightning Talks",
            "discipline" :            "Conference",
            "date" :                  "2012-01-14",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSS@RIT gives a lightning talk on student and academic engagement.",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://fedoraproject.org/wiki/FUDCon:Blacksburg_2012_lightning_talks"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FUDCon Blacksburg - Workshops",
            "discipline" :            "Hackathon",
            "date" :                  "2012-01-13",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT students participate in the FUDCon Blacksburg Hackaton.",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://fedoraproject.org/wiki/FUDCon:Blacksburg_2012#Hackfests_.26_Workshops"
        },
        {   "type" :                  "Conference",
            "label" :                 "FUDCon Blacksburg - Barcamp Sessions",
            "discipline" :            "Conference",
            "date" :                  "2012-01-14",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSS@RIT attends FUDCon Blacksburg to show off OLPC Projects and RIT Remixerator.",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://fedoraproject.org/wiki/FUDCon:Blacksburg_2012"
        },
        {
            "type" :                  "Conference",
            "label" :                 "PyCon 2012",
            "discipline" :            "Conference",
            "date" :                  "2012-03-09",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSS@RIT attends PyCon and gives poster sessions on python related work.",
            "imageURL" :              "meninblack.png",
            "url" :                   "https://us.pycon.org/2012/"
        },
        {   "type" :                  "Conference",
            "label" :                 "Startup Weekend Rochester",
            "discipline" :            "Conference",
            "date" :                  "2012-04-29",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSS@RIT participates in 54-hour event focused on developing mobile apps.",
            "imageURL" :              "meninblack.png",
            "url" :                   "http://rochester.startupweekend.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "2nd ARM Developer Day @ RIT",
            "discipline" :            "Event",
            "date" :                  "2012-01-24",
            "relationship" :          "Event",
            "relationship-detail" :   "Second ARM Developer Day @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://armdeveloperday2nd.wordpress.com//"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-04",
            "imageURL": "games_research.png",
            "relationship-detail": "Initialized blogs, learned IRC, and created accounts on github.",
            "type": "Games Research",
            "label": "Initialized blogs, learned IRC, and created accounts on github."
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-04",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Preliminary Research document to store all rough drafts, charts, and summaries for individual papers",
            "type": "Games Research",
            "label": "Started Preliminary Research document to store all rough drafts, charts, and summaries for individual papers"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-05",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Research Essays document",
            "type": "Games Research",
            "label": "Started Research Essays document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-05",
            "imageURL": "games_research.png",
            "relationship-detail": "Started User Generated Content Info document for research into User Generated Content",
            "type": "Games Research",
            "label": "Started User Generated Content Info document for research into User Generated Content"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-05",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed User Generated Content Info document",
            "type": "Games Research",
            "label": "Completed User Generated Content Info document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-07",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Preliminary Research document",
            "type": "Games Research",
            "label": "Completed Preliminary Research document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-11",
            "imageURL": "games_research.png",
            "relationship-detail": "Researched real money trading, geosocial services, etc",
            "type": "Games Research",
            "label": "Researched real money trading, geosocial services, etc"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-11",
            "imageURL": "games_research.png",
            "relationship-detail": "Playtested MMORPG and social games",
            "type": "Games Research",
            "label": "Playtested MMORPG and social games"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-11",
            "imageURL": "games_research.png",
            "relationship-detail": "Investigated open source tech and completed a general analyses survey for each",
            "type": "Games Research",
            "label": "Investigated open source tech and completed a general analyses survey for each"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-12",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Research Outlines document to summarize our results for the initial questions from SJ",
            "type": "Games Research",
            "label": "Started Research Outlines document to summarize our results for the initial questions from SJ"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-12",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Research Outlines document",
            "type": "Games Research",
            "label": "Completed Research Outlines document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Game Analysis Matrix spreadsheet to store all game analyses in an easy to view matrix",
            "type": "Games Research",
            "label": "Started Game Analysis Matrix spreadsheet to store all game analyses in an easy to view matrix"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-14",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Game Analysis Matrix spreadsheet",
            "type": "Games Research",
            "label": "Completed Game Analysis Matrix spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-14",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Open Source Tech Matrix spreadsheet to store all open technology info in an easy to view matrix",
            "type": "Games Research",
            "label": "Started Open Source Tech Matrix spreadsheet to store all open technology info in an easy to view matrix"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-14",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Open Source Tech Analysis document to store all open technology  analyses in an easy to view matrix",
            "type": "Games Research",
            "label": "Started Open Source Tech Analysis document to store all open technology  analyses in an easy to view matrix"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Started RPG and Social Game Mechanics spreadsheet to store all game mechanic information in an easy to view matrix",
            "type": "Games Research",
            "label": "Started RPG and Social Game Mechanics spreadsheet to store all game mechanic information in an easy to view matrix"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Game Analyses document",
            "type": "Games Research",
            "label": "Completed Game Analyses document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Open Source Tech Matrix spreadsheet",
            "type": "Games Research",
            "label": "Completed Open Source Tech Matrix spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-19",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed RPG and Social Game Mechanics spreadsheet",
            "type": "Games Research",
            "label": "Completed RPG and Social Game Mechanics spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-19",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Game Analysis Quicklook spreadsheet to store all Game Analyses information in an easy to view matrix",
            "type": "Games Research",
            "label": "Started Game Analysis Quicklook spreadsheet to store all Game Analyses information in an easy to view matrix"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-19",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Game Analysis Quicklook spreadsheet",
            "type": "Games Research",
            "label": "Completed Game Analysis Quicklook spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-19",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Open Source Tech Analysis doc",
            "type": "Games Research",
            "label": "Completed Open Source Tech Analysis doc"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-19",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Open Source Tech Quicklook spreadshee\t",
            "type": "Games Research",
            "label": "Completed Open Source Tech Quicklook spreadshee\t"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-20",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Commarch Thoughts on Game Tech document to determine what group members thought of each technology",
            "type": "Games Research",
            "label": "Started Commarch Thoughts on Game Tech document to determine what group members thought of each technology"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-20",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Commarch Thoughts on Game Tech document",
            "type": "Games Research",
            "label": "Completed Commarch Thoughts on Game Tech document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-21",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Plan for 6/21-6/29 spreadsheet",
            "type": "Games Research",
            "label": "Started Plan for 6/21-6/29 spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-21",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Plan for 6/21-6/29 spreadsheet",
            "type": "Games Research",
            "label": "Completed Plan for 6/21-6/29 spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-21",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Contact Vitals document",
            "type": "Games Research",
            "label": "Started Contact Vitals document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-22",
            "imageURL": "games_research.png",
            "relationship-detail": "Sent up-to-date work to RedHat for review",
            "type": "Games Research",
            "label": "Sent up-to-date work to RedHat for review"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Playtested various RPGs including Super Mario RPG, FF1, Ocarina of Time, Earthbound, and Secret of Mana",
            "type": "Games Research",
            "label": "Playtested various RPGs including Super Mario RPG, FF1, Ocarina of Time, Earthbound, and Secret of Mana"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-25",
            "imageURL": "games_research.png",
            "relationship-detail": "Received feedback from RedHat",
            "type": "Games Research",
            "label": "Received feedback from RedHat"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-25",
            "imageURL": "games_research.png",
            "relationship-detail": "Contacted various Open Source collectives and companies",
            "type": "Games Research",
            "label": "Contacted various Open Source collectives and companies"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Began designing combat systems, mechanics, and setting",
            "type": "Games Research",
            "label": "Began designing combat systems, mechanics, and setting"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Game experience brainstorming session",
            "type": "Games Research",
            "label": "Game experience brainstorming session"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Brainstorming Game Experience document to hold information from brainstorming session ",
            "type": "Games Research",
            "label": "Started Brainstorming Game Experience document to hold information from brainstorming session "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Discussed MDA (Mechanics, Dynamics, Aesthetics)",
            "type": "Games Research",
            "label": "Discussed MDA (Mechanics, Dynamics, Aesthetics)"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-27",
            "imageURL": "games_research.png",
            "relationship-detail": "Contact Status spreadsheet started",
            "type": "Games Research",
            "label": "Contact Status spreadsheet started"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-27",
            "imageURL": "games_research.png",
            "relationship-detail": "Brainstormed negative elements within games",
            "type": "Games Research",
            "label": "Brainstormed negative elements within games"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-28",
            "imageURL": "games_research.png",
            "relationship-detail": "Contact Status spreadsheet completed",
            "type": "Games Research",
            "label": "Contact Status spreadsheet completed"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-28",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Contact Vitas document",
            "type": "Games Research",
            "label": "Completed Contact Vitas document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-28",
            "imageURL": "games_research.png",
            "relationship-detail": "Outreach Responses document started",
            "type": "Games Research",
            "label": "Outreach Responses document started"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-29",
            "imageURL": "games_research.png",
            "relationship-detail": "Outreach Responses document completed",
            "type": "Games Research",
            "label": "Outreach Responses document completed"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-02",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Game Definitions document",
            "type": "Games Research",
            "label": "Started Game Definitions document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-02",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Game Definitions document",
            "type": "Games Research",
            "label": "Completed Game Definitions document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-02",
            "imageURL": "games_research.png",
            "relationship-detail": "Begin development of charsheet, develop base of app",
            "type": "Games Research",
            "label": "Begin development of charsheet, develop base of app"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-05",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Prototype Ideas document to hold information about our Initial paper prototype",
            "type": "Games Research",
            "label": "Started Prototype Ideas document to hold information about our Initial paper prototype"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-06-06",
            "imageURL": "games_research.png",
            "relationship-detail": "Molded game system with the setting",
            "type": "Games Research",
            "label": "Molded game system with the setting"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-09",
            "imageURL": "games_research.png",
            "relationship-detail": "Started High Concept document ",
            "type": "Games Research",
            "label": "Started High Concept document "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-09",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Game Treatment document",
            "type": "Games Research",
            "label": "Started Game Treatment document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-09",
            "imageURL": "games_research.png",
            "relationship-detail": "Pull charsheet data in from various sources, work on base functionality and styling",
            "type": "Games Research",
            "label": "Pull charsheet data in from various sources, work on base functionality and styling"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-10",
            "imageURL": "games_research.png",
            "relationship-detail": "Started API Master Doc ",
            "type": "Games Research",
            "label": "Started API Master Doc "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-12",
            "imageURL": "games_research.png",
            "relationship-detail": "Discussed choice FOSS elements to integrate and implement",
            "type": "Games Research",
            "label": "Discussed choice FOSS elements to integrate and implement"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Created basic design and feel of the game in the High Concept Document and Game Treatment Document",
            "type": "Games Research",
            "label": "Created basic design and feel of the game in the High Concept Document and Game Treatment Document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Added a backstory to the Game Treatment document to fit with the look and feel of the setting",
            "type": "Games Research",
            "label": "Added a backstory to the Game Treatment document to fit with the look and feel of the setting"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed API Master Doc",
            "type": "Games Research",
            "label": "Completed API Master Doc"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Had a Symposium meeting with the other fellows of the program",
            "type": "Games Research",
            "label": "Had a Symposium meeting with the other fellows of the program"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Project Abstract document for the 2012 RIT Ugrad Research Symposium",
            "type": "Games Research",
            "label": "Started Project Abstract document for the 2012 RIT Ugrad Research Symposium"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Added combat paper prototype to the Prototype Ideas document",
            "type": "Games Research",
            "label": "Added combat paper prototype to the Prototype Ideas document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Discussed ideas surrounding the economy",
            "type": "Games Research",
            "label": "Discussed ideas surrounding the economy"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Read and discussed Game Balance Concepts (All 10 weeks)",
            "type": "Games Research",
            "label": "Read and discussed Game Balance Concepts (All 10 weeks)"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Add a bunch of features, error handling, close many tickets",
            "type": "Games Research",
            "label": "Add a bunch of features, error handling, close many tickets"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-16",
            "imageURL": "games_research.png",
            "relationship-detail": "Worked on various systems such as trading, crafting, armor, and combat",
            "type": "Games Research",
            "label": "Worked on various systems such as trading, crafting, armor, and combat"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Project Abstract document and submitted",
            "type": "Games Research",
            "label": "Completed Project Abstract document and submitted"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-18",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Presentation Day To Do List document",
            "type": "Games Research",
            "label": "Started Presentation Day To Do List document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-23",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed High Concept document",
            "type": "Games Research",
            "label": "Completed High Concept document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-23",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Game Treatment document",
            "type": "Games Research",
            "label": "Completed Game Treatment document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-23",
            "imageURL": "games_research.png",
            "relationship-detail": "Balance work on the combat, crafting and materials systems",
            "type": "Games Research",
            "label": "Balance work on the combat, crafting and materials systems"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-23",
            "imageURL": "games_research.png",
            "relationship-detail": "Testing combat prototype",
            "type": "Games Research",
            "label": "Testing combat prototype"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-23",
            "imageURL": "games_research.png",
            "relationship-detail": "Deployment to OpenShift, add more features, work on integrating more APIs",
            "type": "Games Research",
            "label": "Deployment to OpenShift, add more features, work on integrating more APIs"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-24",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Weapons vs Armor spreadsheet",
            "type": "Games Research",
            "label": "Started Weapons vs Armor spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-24",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Weapons vs Armor spreadsheet",
            "type": "Games Research",
            "label": "Completed Weapons vs Armor spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-25",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Languages Spreadsheet ",
            "type": "Games Research",
            "label": "Started Languages Spreadsheet "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-25",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Languages Spreadsheet",
            "type": "Games Research",
            "label": "Completed Languages Spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-25",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Developer Character Spreadsheet",
            "type": "Games Research",
            "label": "Started Developer Character Spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Playtest Scripts and Surveys document",
            "type": "Games Research",
            "label": "Started Playtest Scripts and Surveys document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Coding Rates spreadsheet started",
            "type": "Games Research",
            "label": "Coding Rates spreadsheet started"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Coding Rates spreadsheet completed",
            "type": "Games Research",
            "label": "Coding Rates spreadsheet completed"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-26",
            "imageURL": "games_research.png",
            "relationship-detail": "Completed Developer Character Spreadsheet",
            "type": "Games Research",
            "label": "Completed Developer Character Spreadsheet"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-27",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Playtest Flyer and preparations for playtesting",
            "type": "Games Research",
            "label": "Started Playtest Flyer and preparations for playtesting"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-27",
            "imageURL": "games_research.png",
            "relationship-detail": "Added FOSS integration numbers and balance to Brainstorming Ideas document",
            "type": "Games Research",
            "label": "Added FOSS integration numbers and balance to Brainstorming Ideas document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-27",
            "imageURL": "games_research.png",
            "relationship-detail": "Added stat ratios for Developer Character Sheet document",
            "type": "Games Research",
            "label": "Added stat ratios for Developer Character Sheet document"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Game Systems, a compilation of the various systems we developed",
            "type": "Games Research",
            "label": "Started Game Systems, a compilation of the various systems we developed"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Game Systems doc completed",
            "type": "Games Research",
            "label": "Game Systems doc completed"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Playtest flyers posted around campus",
            "type": "Games Research",
            "label": "Playtest flyers posted around campus"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Implement attributes and skill values, more improvements and additions",
            "type": "Games Research",
            "label": "Implement attributes and skill values, more improvements and additions"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Started PowerPoint presentation we\u2019ll use at the Research Symposium",
            "type": "Games Research",
            "label": "Started PowerPoint presentation we\u2019ll use at the Research Symposium"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-30",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Presentation Outline",
            "type": "Games Research",
            "label": "Started Presentation Outline"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-31",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Timeline of our progress ",
            "type": "Games Research",
            "label": "Started Timeline of our progress "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-07-31",
            "imageURL": "games_research.png",
            "relationship-detail": "Started Presentation Script",
            "type": "Games Research",
            "label": "Started Presentation Script"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-08-03",
            "imageURL": "games_research.png",
            "relationship-detail": "Playtest session with other fellows ",
            "type": "Games Research",
            "label": "Playtest session with other fellows "
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-08-06",
            "imageURL": "games_research.png",
            "relationship-detail": "Prepare presentation",
            "type": "Games Research",
            "label": "Prepare presentation"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-08-09",
            "imageURL": "games_research.png",
            "relationship-detail": "Go to Red Hat in Boston to give presentation",
            "type": "Games Research",
            "label": "Go to Red Hat in Boston to give presentation"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-08-11",
            "imageURL": "games_research.png",
            "relationship-detail": "See Boston",
            "type": "Games Research",
            "label": "See Boston"
        },
        {
            "discipline": "Games Research",
            "url": "http://foss.rit.edu/projects/fosssgm",
            "relationship": "Games Research",
            "date": "2012-08-13",
            "imageURL": "games_research.png",
            "relationship-detail": "Clean up any documents",
            "type": "Games Research",
            "label": "Clean up any documents"
        }
    ]
}
